M48
; DRILL file {KiCad (6.0.5)} date Tue Jun  7 13:10:20 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-07T13:10:20+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X149.7Y-137.55
X149.7Y-145.55
T2
X150.775Y-58.9
X173.9Y-84.225
T3
X118.5Y-73.0
X118.5Y-137.0
X182.5Y-73.0
X182.5Y-137.0
T0
M30
